name: Publish Docker image
on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.SECRET_MAIN }}
          password: ${{ secrets.secret_main}}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker_hub_name/image_name:latest
          secrets: |
            "MYSQL_HOST=${{ secrets.MYSQL_HOST}}"
            "MYSQL_USER=${{ secrets.MYSQL_USER}}"
            "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD}}"
            "MYSQL_PORT=${{ secrets.MYSQL_PORT }}"
